### ISSUE TITLE
Chromosome  undefined 

### ISSUE THREAD

**Issue by uqmwu** [wwood/dirseq#7]
Hi Ben，
Now I have installed dirseq and tried with the example you provided, no issue. 
But when I use it for my data, I have got the following error: 

 INFO dirseq 24/06 12:08:52: Running command: sed '/^##FASTA$/,$d' "/scratch/project/alkane/C3_anammox/C3_anammox_BINNING/prokka_anotate/prokka_out/bin.0/bin.0.gff" > /scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3
 INFO dirseq 24/06 12:08:52: Command finished with exitstatus 0
 INFO dirseq 24/06 12:08:52: Listing contigs in sorted order ..
 INFO dirseq 24/06 12:08:52: Running command: samtools idxstats "/scratch/project/alkane/C3_anammox/bam_filter/bin.0.bam" |cut -f1,2 |grep -v '^*' >"/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o"
 INFO dirseq 24/06 12:08:52: Command finished with exitstatus 0
 INFO dirseq 24/06 12:08:52: Finding featureless contigs
 INFO dirseq 24/06 12:08:52: Running command: grep -v '^#' "/scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3" |cut -f1 |sort |uniq |grep -vFw -f /dev/stdin "/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o" |cut -f1
 INFO dirseq 24/06 12:08:52: Command finished with exitstatus 0
 INFO dirseq 24/06 12:08:52: Found 596 featureless contigs
 INFO dirseq 24/06 12:08:52: Running bedtools sort
 INFO dirseq 24/06 12:08:52: Running command: cat /scratch/user/uqmwu4/tmp/extra_features20220624-16987-cz5y3.gff "/scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3" |bedtools sort -i /dev/stdin -faidx "/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o" >"/scratch/user/uqmwu4/tmp/sorted_gff20220624-16987-ayr8yn.gff3"
 INFO dirseq 24/06 12:08:52: Command finished with exitstatus 1
/home/uqmwu4/.gem/ruby/gems/bio-commandeer-0.4.0/lib/bio-commandeer/commandeer.rb:62:in `raise_if_failed': Command returned non-zero exit status (1), likely indicating failure. Command run was cat /scratch/user/uqmwu4/tmp/extra_features20220624-16987-cz5y3.gff "/scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3" |bedtools sort -i /dev/stdin -faidx "/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o" >"/scratch/user/uqmwu4/tmp/sorted_gff20220624-16987-ayr8yn.gff3" and the STDERR was: (Bio::CommandFailedException)
Chromosome "k141_100310_length_12288" undefined in /scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o

The bam file was generated using coverM make and then filtered using coverM filter. 
So what is the issue here? Thanks!

**Comment by wwood** [comment]
Hi,

This looks to me as if the BAM files where not made by mapping to the same set of contigs that went into the bin itself. So they have different names, does that sound plausible?

**Comment by wwood** [comment]
Hmm, would you mind sending the data to me somehow and the command line that you used? E.g. via cloudstor to my QUT email account, please? Hard to know from that log.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: uqmwu ***@***.***>
Sent: Friday, June 24, 2022 2:52:20 PM
To: wwood/dirseq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/dirseq] Chromosome undefined (Issue #7)


Hi Ben，
Now I have installed dirseq and tried with the example you provided, no issue.
But when I use it for my data, I have got the following error:

INFO dirseq 24/06 12:08:52: Running command: sed '/^##FASTA$/,$d' "/scratch/project/alkane/C3_anammox/C3_anammox_BINNING/prokka_anotate/prokka_out/bin.0/bin.0.gff" > /scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3
INFO dirseq 24/06 12:08:52: Command finished with exitstatus 0
INFO dirseq 24/06 12:08:52: Listing contigs in sorted order ..
INFO dirseq 24/06 12:08:52: Running command: samtools idxstats "/scratch/project/alkane/C3_anammox/bam_filter/bin.0.bam" |cut -f1,2 |grep -v '^*' >"/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o"
INFO dirseq 24/06 12:08:52: Command finished with exitstatus 0
INFO dirseq 24/06 12:08:52: Finding featureless contigs
INFO dirseq 24/06 12:08:52: Running command: grep -v '^#' "/scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3" |cut -f1 |sort |uniq |grep -vFw -f /dev/stdin "/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o" |cut -f1
INFO dirseq 24/06 12:08:52: Command finished with exitstatus 0
INFO dirseq 24/06 12:08:52: Found 596 featureless contigs
INFO dirseq 24/06 12:08:52: Running bedtools sort
INFO dirseq 24/06 12:08:52: Running command: cat /scratch/user/uqmwu4/tmp/extra_features20220624-16987-cz5y3.gff "/scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3" |bedtools sort -i /dev/stdin -faidx "/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o" >"/scratch/user/uqmwu4/tmp/sorted_gff20220624-16987-ayr8yn.gff3"
INFO dirseq 24/06 12:08:52: Command finished with exitstatus 1
/home/uqmwu4/.gem/ruby/gems/bio-commandeer-0.4.0/lib/bio-commandeer/commandeer.rb:62:in `raise_if_failed': Command returned non-zero exit status (1), likely indicating failure. Command run was cat /scratch/user/uqmwu4/tmp/extra_features20220624-16987-cz5y3.gff "/scratch/user/uqmwu4/tmp/dirseq20220624-16987-cnw3os.gff3" |bedtools sort -i /dev/stdin -faidx "/scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o" >"/scratch/user/uqmwu4/tmp/sorted_gff20220624-16987-ayr8yn.gff3" and the STDERR was: (Bio::CommandFailedException)
Chromosome "k141_100310_length_12288" undefined in /scratch/user/uqmwu4/tmp/bam_contigs20220624-16987-1othn1o

The bam file was generated using coverM make and then filtered using coverM filter.
So what is the issue here? Thanks!

―
